
import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";import {io} from "socket.io-client";import "./style.css";
const API=import.meta.env.VITE_API_URL||"http://localhost:4000";const money=l=>`₹${(l/100).toFixed(2)} Cr`;
const inc=b=>b<=100?5:b<=200?10:b<=500?15:20;
function Timer({target}){const [n,setN]=useState(0);useEffect(()=>{const f=()=>setN(Math.max(0,(new Date(target)-Date.now())/1000));f();const t=setInterval(f,100);return()=>clearInterval(t)},[target]);return <b className={n<3?"danger":""}>{n.toFixed(1)}s</b>}
function Card({p,compact=false}){if(!p)return null;return <div className={"card "+(compact?"compact":"")}><span className="tag">{p.specialism}</span><h2>{p.full_name}</h2><div className="muted">{p.country} · {p.status}</div><div className="points">★ {p.points} <small>POINTS</small></div><div className="muted">Base {money(p.reserve_price_lakh)}</div></div>}
function App(){
 const [token,setToken]=useState(localStorage.token||""),[me,setMe]=useState(JSON.parse(localStorage.me||"null")), [page,setPage]=useState(token?"home":"login"),[err,setErr]=useState("");
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState(""),[room,setRoom]=useState(""),[state,setState]=useState(null),[sock,setSock]=useState(null),[forfeit,setForfeit]=useState(null);
 useEffect(()=>{if(!token)return;const s=io(API,{auth:{token}});s.on("state",setState);s.on("forfeit",setForfeit);setSock(s);return()=>s.close()},[token]);
 const auth=async type=>{try{const r=await fetch(API+"/api/auth/"+type,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(type==="register"?{email,password,displayName:name}:{email,password})});const d=await r.json();if(!r.ok)throw Error(d.error);localStorage.token=d.token;localStorage.me=JSON.stringify(d.user);setToken(d.token);setMe(d.user);setPage("home")}catch(e){setErr(e.message)}};
 const action=(ev,data)=>sock?.emit(ev,data,r=>{if(!r?.ok)setErr(r.error)});
 const p=state?.participants?.[me?.id],current=state?.players?.[state?.currentPlayerId], next=state?.currentBidLakh==null?current?.reserve_price_lakh:(state.currentBidLakh+inc(state.currentBidLakh));
 const results=useMemo(()=>{if(state?.status!=="FINISHED")return [];return Object.entries(state.participants||{}).map(([id,x])=>{const team=(state.teamPlayers?.[id]||[]),pts=team.reduce((a,p)=>a+p.points,0),bonus=Math.floor(x.budgetLakh/10);return {...x,id,team,pts,bonus,total:pts+bonus}})},[state]);
 if(!token)return <Auth page={page} setPage={setPage} email={email} setEmail={setEmail} password={password} setPassword={setPassword} name={name} setName={setName} auth={auth} err={err}/>;
 if(page==="home")return <div className="center"><div className="panel"><Logo/><p>Real-time 1v1 IPL auction strategy game.</p><button onClick={()=>action("create_room",{})}>CREATE GAME</button><div className="join"><input placeholder="ROOM CODE" value={room} onChange={e=>setRoom(e.target.value.toUpperCase())}/><button onClick={()=>action("join_room",{roomCode:room})}>JOIN</button></div>{me?.is_admin&&<button className="ghost" onClick={()=>setPage("admin")}>ADMIN</button>}<button className="ghost" onClick={()=>{localStorage.clear();location.reload()}}>LOG OUT</button>{err&&<div className="error">{err}</div>}</div></div>;
 if(page==="admin")return <Admin token={token} back={()=>setPage("home")}/>;
 if(state?.status==="LOBBY")return <Lobby state={state} me={me} action={action} err={err}/>;
 return <Game state={state} me={me} p={p} current={current} next={next} action={action} results={results} forfeit={forfeit}/>;
}
function Logo(){return <><div className="eyebrow">PARADOX '26</div><h1>IPL BID WAR</h1></>}
function Auth({page,setPage,email,setEmail,password,setPassword,name,setName,auth,err}){return <div className="center"><div className="panel"><Logo/>{page==="register"&&<input placeholder="DISPLAY NAME" value={name} onChange={e=>setName(e.target.value)}/>}<input placeholder="EMAIL" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="PASSWORD" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={()=>auth(page==="register"?"register":"login")}>{page==="register"?"CREATE ACCOUNT":"LOGIN"}</button><button className="ghost" onClick={()=>setPage(page==="login"?"register":"login")}>{page==="login"?"CREATE ACCOUNT":"BACK TO LOGIN"}</button>{err&&<div className="error">{err}</div>}</div></div>}
function Lobby({state,me,action,err}){return <div className="center"><div className="panel"><div className="eyebrow">ROOM CODE</div><h1>{state.roomCode}</h1><div className="lobby">{Object.entries(state.participants).map(([id,p])=><div key={id}><span>PLAYER {p.slot}</span><b>{id===me.id?"YOU":"OPPONENT"}</b><small>{p.ready?"READY":"WAITING"}</small></div>)}</div><button onClick={()=>action("ready",{gameId:state.gameId})}>READY</button>{err&&<div className="error">{err}</div>}</div></div>}
function Game({state,me,p,current,next,action,results,forfeit}){
 const [tab,setTab]=useState("auction");const opponent=Object.entries(state.participants).find(([id])=>id!==me.id)?.[1];const myTeam=state.teamPlayers?.[me.id]||[];const oppId=Object.keys(state.participants).find(id=>id!==me.id);const oppTeam=state.teamPlayers?.[oppId]||[];
 return <main><header><div><b>PARADOX '26</b><span> · {state.roomCode}</span></div><div>{state.status}</div></header>
 <div className="topbar"><span>ROUND {Math.min(state.currentIndex+1,5)} / 5</span>{state.status==="STRATEGY"?<Timer target={state.strategyEndsAt}/>:state.status==="AUCTION"&&<Timer target={state.auctionEndsAt}/>}</div>
 {state.status==="STRATEGY"&&<section><h1>STRATEGY PHASE</h1><p className="muted">You have 3 minutes. Study all five players before bidding begins.</p><div className="grid">{state.pool.map(id=><Card key={id} p={state.players[id]}/>)}</div></section>}
 {state.status==="AUCTION"&&<section className="auction"><div><Card p={current}/><div className="unsold"><b>UNSOLD</b>{state.unsold.map(id=><span key={id}>{state.players[id]?.full_name}</span>)}</div></div><div className="bidbox"><span className="eyebrow">CURRENT BID</span><strong>{state.currentBidLakh==null?"BASE PRICE":money(state.currentBidLakh)}</strong><span className="muted">{state.currentBidderId?(state.currentBidderId===me.id?"YOU":"OPPONENT"):"NO BID YET"}</span><button disabled={state.currentBidderId===me.id||next>p.budgetLakh} onClick={()=>action("place_bid",{gameId:state.gameId})}>BID {money(next||0)}</button><small>YOUR BUDGET {money(p.budgetLakh)}</small></div></section>}
 {state.status==="FINISHED"&&<Result results={results} me={me} forfeit={forfeit}/>}
 <section className="columns"><div><div className="sectionhead"><h3>YOUR TEAM</h3><b>{money(p?.budgetLakh||0)}</b></div>{myTeam.map(x=><Card key={x.id} p={x} compact/>)}{!myTeam.length&&<p className="muted">No players won.</p>}</div><div><div className="sectionhead"><h3>OPPONENT</h3><b>{money(opponent?.budgetLakh||0)}</b></div>{oppTeam.map(x=><Card key={x.id} p={x} compact/>)}{!oppTeam.length&&<p className="muted">No players won.</p>}</div></section>
 </main>
}
function Result({results,me,forfeit}){const sorted=[...results].sort((a,b)=>b.total-a.total);return <section className="result"><div className="eyebrow">FINAL RESULT</div><h1>{forfeit?"OPPONENT WINS BY FORFEIT":sorted[0]?.id===me.id?"YOU WIN":"OPPONENT WINS"}</h1><div className="scoregrid">{sorted.map(x=><div className={"score "+(x.id===me.id?"mine":"")} key={x.id}><span>PLAYER {x.slot}</span><strong>{x.total}</strong><small>{x.pts} player points + {x.bonus} budget bonus</small><small>Remaining {money(x.budgetLakh)} · {x.team.length} players</small></div>)}</div></section>}
function Admin({token,back}){const [players,setPlayers]=useState([]),[q,setQ]=useState(""),[msg,setMsg]=useState("");
 useEffect(()=>{fetch(API+"/api/players",{headers:{Authorization:"Bearer "+token}}).then(r=>r.json()).then(setPlayers)},[token]);
 const save=async(p)=>{const r=await fetch(API+"/api/admin/players/"+p.id,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({points:p.points,reserve_price_lakh:p.reserve_price_lakh})});const d=await r.json();if(r.ok){setPlayers(x=>x.map(a=>a.id===p.id?d:a));setMsg("Saved")}};
 const list=players.filter(p=>p.full_name.toLowerCase().includes(q.toLowerCase())).slice(0,50);
 return <main><header><b>ADMIN · PLAYER CATALOGUE</b><button className="ghost" onClick={back}>BACK</button></header><section><input className="search" placeholder="SEARCH PLAYER" value={q} onChange={e=>setQ(e.target.value)}/>{list.map(p=><div className="adminrow" key={p.id}><div><b>{p.full_name}</b><small>{p.country} · {p.specialism}</small></div><label>Points<input type="number" value={p.points} onChange={e=>setPlayers(x=>x.map(a=>a.id===p.id?{...a,points:+e.target.value}:a))}/></label><label>Base (lakh)<input type="number" value={p.reserve_price_lakh} onChange={e=>setPlayers(x=>x.map(a=>a.id===p.id?{...a,reserve_price_lakh:+e.target.value}:a))}/></label><button onClick={()=>save(p)}>SAVE</button></div>)}{msg&&<div className="toast">{msg}</div>}</section></main>}
createRoot(document.getElementById("root")).render(<App/>);
